-- DDL (for PostgreSQL)
CREATE TABLE IF NOT EXISTS DEPARTMENT(PK_DEP_ID INTEGER,NAME VARCHAR(80),PRIMARY KEY(PK_DEP_ID));
COMMENT ON TABLE DEPARTMENT IS 'Department of ACME Inc.';
COMMENT ON COLUMN DEPARTMENT.PK_DEP_ID IS 'Primary key of table DEPARTMENT';
COMMENT ON COLUMN DEPARTMENT.NAME IS 'Name of the department';
CREATE TABLE IF NOT EXISTS EMPLOYEE(PK_EMP_ID INTEGER,NAME VARCHAR(80),FIRST_MAME VARCHAR(80),DATE_OF_BIRTH DATE,DATE_OF_HIRE DATE,PRIMARY KEY(PK_EMP_ID));
COMMENT ON TABLE EMPLOYEE IS 'Employees of ACME Inc.';
COMMENT ON COLUMN EMPLOYEE.PK_EMP_ID IS 'Primary key of table EMPLOYEE';
COMMENT ON COLUMN EMPLOYEE.NAME IS 'Family name of the employee';
COMMENT ON COLUMN EMPLOYEE.FIRST_MAME IS 'First name of the employee';
COMMENT ON COLUMN EMPLOYEE.DATE_OF_BIRTH IS 'Date of birth of the employee';
COMMENT ON COLUMN EMPLOYEE.DATE_OF_HIRE IS 'Date, when the employee was hired';
CREATE TABLE IF NOT EXISTS EMPLOYEE_DEPARTMENT(
    FK_DEP_ID INTEGER ,
    FK_EMP_ID INTEGER,
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY (FK_DEP_ID) REFERENCES DEPARTMENT(PK_DEP_ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (FK_EMP_ID) REFERENCES EMPLOYEE(PK_EMP_ID));

COMMENT ON TABLE EMPLOYEE_DEPARTMENT IS 'Assignment of employees to departments';

